export { ContentAuthor } from './ContentAuthor'
export { ContentBlock } from './ContentBlock'
export { ContentCard } from './ContentCard'
export { ContentDate } from './ContentDate'
export { ContentImageCard } from './ContentImageCard'
export { ContentPage } from './ContentPage'
export { ContentTags } from './ContentTags'

// TODO: extrair esses services para suas pastas
export { default as pagesContentService } from './page-content-service'
export { default as sociaContentService } from './socia-content-service'
export { default as parceriaContentService } from './parceria-content-service'
export { default as servicoContentService } from './servico-content-service'
export { default as depoimentoContentService } from './depoimento-content-service'
export { default as portfolioContentService } from './portfolio-content-service'
export { default as postContentService } from './post-content-service'
