export { ContentAuthor } from './ContentAuthor'
export { ContentBlock } from './ContentBlock'
export { ContentCard } from './ContentCard'
export { ContentDate } from './ContentDate'
export { ContentImageCard } from './ContentImageCard'
export { ContentPage } from './ContentPage'
export { ContentTags } from './ContentTags'
export { ContentPageHeader } from './ContentPageHeader'

// TODO: extrair esses services para suas pastas
export { pagesContentService } from './services'
export { sociaContentService } from './services'
export { parceriaContentService } from './services'
export { servicoContentService } from './services'
export { depoimentoContentService } from './services'
export { portfolioContentService } from './services'
export { postContentService } from './services'
